# Generated by Django 3.0.7 on 2020-06-25 18:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200625_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['subreddit__slug', 'title'], unique=True, verbose_name='Post url slug'),
        ),
    ]
