# Generated by Django 3.0.7 on 2020-06-25 18:49

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200625_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique=True, verbose_name='Post url slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subreddit_slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='subreddit__slug', unique=True, verbose_name='Post url slug'),
            preserve_default=False,
        ),
    ]
