# Generated by Django 3.0.7 on 2020-06-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_subreddit_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_slug',
            new_name='slug',
        ),
    ]
