# Generated by Django 3.0.7 on 2020-07-02 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_postvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvotes',
            name='vote',
            field=models.IntegerField(choices=[(-1, 'downvote'), (0, 'no vote'), (1, 'upvote')], default=None),
        ),
        migrations.AlterUniqueTogether(
            name='postvotes',
            unique_together={('post_id', 'user_id')},
        ),
    ]
