# Generated by Django 3.0.7 on 2020-07-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200703_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='posts.PostComment'),
        ),
    ]
