# Generated by Django 3.0.7 on 2020-07-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postcomment_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='children',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='posts.PostComment'),
        ),
    ]
