# Generated by Django 3.0.7 on 2020-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200704_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='tldr',
            field=models.CharField(default='temp', help_text="Too Long; Didn't Read. Your responce in a nutshell", max_length=56),
            preserve_default=False,
        ),
    ]
