# Generated by Django 3.0.7 on 2020-07-06 20:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_postcomment_tldr'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
